version: '2'
services:
    kingdomofearth-app:
        image: kingdomofearth
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://kingdomofearth-mariadb:3306/kingdomofearth
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kingdomofearth-mariadb:
        extends:
            file: mariadb.yml
            service: kingdomofearth-mariadb
